version: "3.8"

services:
    registry:
        image: registry:2
        container_name: registry
        restart: unless-stopped
        networks:
            - webnet
        ports:
            - 5000:5000
        environment:
            REGISTRY_STORAGE_DELETE_ENABLED: "true"

    registry-ui:
        image: docker-private-hub
        build:
          context: .
          dockerfile: Dockerfile
        container_name: registry-ui
        restart: unless-stopped
        depends_on:
            - registry
        networks:
            - webnet
        ports:
            - 80:80

networks:
    webnet:
